services:
  srvc1:
    container_name: srvcOneCont
    build:
      context: ./srvcOne
      dockerfile: ./srvcOne/Dockerfile
    deploy:
      resources:
        limits:
          memory: 160M
    restart: unless-stopped
    ports:
      - 5187:5000

  srvc2:
    container_name: srvcTwoCont
    build:
      context: ./srvcOne
      dockerfile: ./srvcOne/Dockerfile
    deploy:
      resources:
        limits:
          memory: 160M
    restart: unless-stopped
    ports:
      - 5188:5001
