version: "2"

services:
  srvc_one:
    container_name: srvcOneCont
    build:
      context: ./srvcOne
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          memory: 160M
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - ./srvcOne:/src
